/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uniba.it.gioco.gui;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nikita
 */
public class JFrameMain extends javax.swing.JFrame {
    private JPanel cardsPanel;
    private CardLayout cardLayout;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        initCards();
    }
    
    public void initCards(){
        cardLayout = new CardLayout();
        cardsPanel = new JPanel(cardLayout);
        
        cardsPanel.add(new JPanelMenu(this), "mainMenu");
        cardsPanel.add(new JPanelNuovoGioco(this), "newGame");
        cardsPanel.add(new JPanelPartita(this), "inGame");
       
        getContentPane().add(cardsPanel, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);    
    }
    
     // Metodo per spostarsi alla "card" specificata
    public void showCard(String cardName) {
        cardLayout.show(cardsPanel, cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
