/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uniba.it.gioco.gui;

import static java.awt.Color.black;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import uniba.it.gioco.GameModel;
import uniba.it.gioco.storia.Init;
import uniba.it.gioco.storia.Input;
import uniba.it.gioco.storia.Output;
import uniba.it.gioco.tipi.Giocatore;
import uniba.it.gioco.tipi.Stanza;

/**
 *
 * @author 39379
 */
public class JPanelPartita extends javax.swing.JPanel {

    private List<Stanza> stanze;
    private Giocatore giocatore;
    private JFrameMain jframeMain;
    private GameModel gameModel;
    private Input inputThread;
    private Init init;

    /**
     * Creates new form JPanelPartita
     */
    public JPanelPartita(JFrameMain jframeMain, GameModel gameModel) {
        this.jframeMain = jframeMain;
        this.gameModel = gameModel;
        initComponents();
        setBackground(black);
        
        try {
            init = gameModel.getInit();
            stanze = gameModel.getStanze();
            giocatore = gameModel.getGiocatore();
            if (giocatore != null) {
                String nickname = giocatore.getNickname();
                SwingUtilities.invokeLater(() -> {
                    areaTesto.setText("Il nome del giocatore è: " + nickname + "\n\n\n");
                });

                Output output = new Output(areaTesto, giocatore, containerImmagini);
                output.start();

                inputThread = new Input(inputTesto, giocatore, init, areaTesto, invioButton, output, stanze);
                inputThread.start();
            } else {
                System.out.println("Giocatore non inizializzato");
            }
        } catch (IOException e) {
            e.printStackTrace(); // Gestisci l'eccezione qui
        }
    }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTesto = new javax.swing.JTextArea();
        invioButton = new javax.swing.JButton();
        cancellaButton = new javax.swing.JButton();
        inputTesto = new javax.swing.JTextField();
        containerImmagini = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 0, 0));

        areaTesto.setColumns(20);
        areaTesto.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        areaTesto.setForeground(new java.awt.Color(70, 71, 66));
        areaTesto.setRows(5);
        jScrollPane1.setViewportView(areaTesto);

        invioButton.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        invioButton.setText("Conferma");
        invioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invioButtonActionPerformed(evt);
            }
        });

        cancellaButton.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        cancellaButton.setText("Cancella");
        cancellaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellaButtonActionPerformed(evt);
            }
        });

        inputTesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(containerImmagini, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancellaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(invioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputTesto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputTesto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(containerImmagini, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancellaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputTestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTestoActionPerformed
        // TODO add your handling code here:
        inputThread.inviaComando(inputTesto.getText().trim(), inputTesto); // Passa inputTesto invece di inputTestoCampo
        inputTesto.setText("");
    }//GEN-LAST:event_inputTestoActionPerformed

    private void cancellaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellaButtonActionPerformed
        // TODO add your handling code here:
        inputTesto.setText("");
    }//GEN-LAST:event_cancellaButtonActionPerformed

    private void invioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invioButtonActionPerformed

        inputTesto.setText("");
    }//GEN-LAST:event_invioButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea areaTesto;
    private javax.swing.JButton cancellaButton;
    private javax.swing.JLabel containerImmagini;
    private javax.swing.JTextField inputTesto;
    private javax.swing.JButton invioButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
